# Generated by Django 2.0.4 on 2018-04-21 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ8', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholasticdetail',
            name='last_grade_dropout',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Number must be 12 digits', 'Invalid aadhaar')]),
        ),
    ]
